const actionTypes = {
  LOGIN_SUCCES: 'LOGIN_SUCCES',
  LOGIN_FAIL: 'LOGIN_FAIL',
  REGISTER_SUCCES: 'REGISTER_SUCCES',
  REGISTER_FAIL: 'REGISTER_FAIL',
  LOGOUT: 'LOGOUT',
  GET_POSTS: 'GET_POSTS',
  GET_POSTS_FAIL: 'GET_POSTS_FAIL',
  GET_POSTS_LIMIT: 'GET_POSTS_LIMIT',
  GET_POSTS_LIMIT_FAIL: 'GET_POSTS_LIMIT_FAIL',
};

export default actionTypes;
