const actionTypes = {
  LOGIN_SUCCES: 'LOGIN_SUCCES',
  LOGIN_FAIL: 'LOGIN_FAIL',
  REGISTER_SUCCES: 'REGISTER_SUCCES',
  REGISTER_FAIL: 'REGISTER_FAIL',
  LOGOUT: 'LOGOUT',
};

export default actionTypes;
